GET   http://localhost:3000/expenses/67489778e8e04f2a23225f3b
content-type: application/json

{
    "amount": 125,
    "reason": "WT - spiral"    
}

###
POST   http://localhost:3000/auth/signup
content-type: application/json

{
    "username": "dhanush",
    "email": "dhanushsai1467@gmail.com",
    "password":"Dhanush@2007"
}

###